name: Sync to Hugging Face Hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: huggingface/hub-sync@v0.1.0
        with:
          github_repo_id: ${{ github.repository }}
          huggingface_repo_id: IDHIR/aliexpress-aps-bot
          hf_token: ${{ secrets.MY_HF_TOKEN }} # تأكد أن هذا الاسم يطابق الاسم الذي اخترته في الـ Secrets
          repo_type: space
          space_sdk: docker
