uploads = []
outputs = []

[[generated]]
id = "KxeTI8UDjDK5Ipt5iE-e4"
uri = "file://public/icon-512.png"
type = "image"
title = "generated_image"

[[generated]]
id = "pm3kZM4Bvd7wdJPls43Lm"
uri = "file://public/icon-192.png"
type = "image"
title = "generated_image"
